//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Locations = new HashSet<Location>();
            this.Subscribers = new HashSet<Subscriber>();
        }
    
        public long Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ZipPostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int CountryId { get; set; }
        public int StateProvinceId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Subscriber> Subscribers { get; set; }
    }
}
