//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLogin
    {
        public AppLogin()
        {
            this.EmployeeRoles = new HashSet<EmployeeRole>();
            this.Employees = new HashSet<Employee>();
            this.LoginLogs = new HashSet<LoginLog>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsWebEnabled { get; set; }
        public bool IsMobileEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public int SubscriberId { get; set; }
        public Nullable<bool> IsReset { get; set; }
        public Nullable<System.Guid> ResetLink { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
    }
}
