//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.EmployeeForms = new HashSet<EmployeeForm>();
            this.Locations = new HashSet<Location>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string UniqueNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Notes { get; set; }
        public bool ReceiveReminders { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int SubscriberId { get; set; }
    
        public virtual ICollection<EmployeeForm> EmployeeForms { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
