//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public int Id { get; set; }
        public long FormId { get; set; }
        public int FormVersionId { get; set; }
        public int SubscriberId { get; set; }
        public string Page { get; set; }
        public string DashboardObjs { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FormVersion FormVersion { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual Form Form { get; set; }
    }
}
