//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public int JobId { get; set; }
        public long EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
