//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Dashboards = new HashSet<Dashboard>();
            this.EmployeeForms = new HashSet<EmployeeForm>();
            this.FormQuestions = new HashSet<FormQuestion>();
            this.FormSections = new HashSet<FormSection>();
            this.FormSubmissions = new HashSet<FormSubmission>();
            this.FormVersions = new HashSet<FormVersion>();
            this.Jobs = new HashSet<Job>();
            this.ProjectForms = new HashSet<ProjectForm>();
            this.SubmissionLogs = new HashSet<SubmissionLog>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int SubscriberId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string WebFormUID { get; set; }
        public bool WorkFlowEnabled { get; set; }
        public Nullable<bool> IsPrivateForm { get; set; }
        public bool IsVisibleSection { get; set; }
    
        public virtual ICollection<Dashboard> Dashboards { get; set; }
        public virtual ICollection<EmployeeForm> EmployeeForms { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }
        public virtual Language Language { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual ICollection<FormSection> FormSections { get; set; }
        public virtual ICollection<FormSubmission> FormSubmissions { get; set; }
        public virtual ICollection<FormVersion> FormVersions { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<ProjectForm> ProjectForms { get; set; }
        public virtual ICollection<SubmissionLog> SubmissionLogs { get; set; }
    }
}
