//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormQuestion
    {
        public FormQuestion()
        {
            this.FormAnswers = new HashSet<FormAnswer>();
            this.FormSections = new HashSet<FormSection>();
        }
    
        public long Id { get; set; }
        public string Question { get; set; }
        public string JSONQuestion { get; set; }
        public bool IsDeleted { get; set; }
        public int FormToolsId { get; set; }
        public long FormId { get; set; }
        public int FormVersionId { get; set; }
        public int LanguageId { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<long> ParentQuestionId { get; set; }
    
        public virtual ICollection<FormAnswer> FormAnswers { get; set; }
        public virtual FormVersion FormVersion { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<FormSection> FormSections { get; set; }
        public virtual Form Form { get; set; }
    }
}
