//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSection
    {
        public FormSection()
        {
            this.FormSectionRoles = new HashSet<FormSectionRole>();
        }
    
        public int Id { get; set; }
        public long FormId { get; set; }
        public long FormQueId { get; set; }
        public int VersionId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual FormQuestion FormQuestion { get; set; }
        public virtual ICollection<FormSectionRole> FormSectionRoles { get; set; }
        public virtual FormVersion FormVersion { get; set; }
        public virtual Form Form { get; set; }
    }
}
