//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormVersion
    {
        public FormVersion()
        {
            this.Dashboards = new HashSet<Dashboard>();
            this.FormQuestions = new HashSet<FormQuestion>();
            this.FormSections = new HashSet<FormSection>();
            this.FormSubmissions = new HashSet<FormSubmission>();
        }
    
        public int Id { get; set; }
        public long FormId { get; set; }
        public int Version { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Dashboard> Dashboards { get; set; }
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }
        public virtual ICollection<FormSection> FormSections { get; set; }
        public virtual ICollection<FormSubmission> FormSubmissions { get; set; }
        public virtual Form Form { get; set; }
    }
}
