//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAnswer
    {
        public long Id { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public int ElementType { get; set; }
        public long FormQuestionId { get; set; }
        public long FormSubmissionId { get; set; }
    
        public virtual FormQuestion FormQuestion { get; set; }
        public virtual FormSubmission FormSubmission { get; set; }
    }
}
