//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSectionRole
    {
        public int Id { get; set; }
        public int FormSectionId { get; set; }
        public int RoleId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual FormSection FormSection { get; set; }
        public virtual Role Role { get; set; }
    }
}
