//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public byte[] Signature { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public int CompletedBy { get; set; }
        public System.DateTime CompletedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long FormId { get; set; }
        public long EmployeeId { get; set; }
        public int LocationId { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        public virtual Form Form { get; set; }
    }
}
