//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.FormQuestions = new HashSet<FormQuestion>();
            this.FormSubmissions = new HashSet<FormSubmission>();
            this.LocalStringResources = new HashSet<LocalStringResource>();
            this.SubscriberLanguages = new HashSet<SubscriberLanguage>();
            this.Forms = new HashSet<Form>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LanguageCulture { get; set; }
        public string UniqueSeoCode { get; set; }
        public string FlagImageFileName { get; set; }
        public bool Rtl { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }
        public virtual ICollection<FormSubmission> FormSubmissions { get; set; }
        public virtual ICollection<LocalStringResource> LocalStringResources { get; set; }
        public virtual ICollection<SubscriberLanguage> SubscriberLanguages { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
    }
}
