//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.EmployeeLocations = new HashSet<EmployeeLocation>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClientId { get; set; }
        public int OperationId { get; set; }
        public long AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
