//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalStringResource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsHtml { get; set; }
        public bool IsDeleted { get; set; }
        public int OperationId { get; set; }
        public int LanguageId { get; set; }
        public bool IsMobileEnabled { get; set; }
        public bool IsWebEnabled { get; set; }
        public int SubscriberId { get; set; }
        public int ResourceType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
