//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public long Id { get; set; }
        public string IpAddress { get; set; }
        public string DeviceId { get; set; }
        public System.DateTime LoggedOn { get; set; }
        public string Action { get; set; }
        public long AppLoginId { get; set; }
    
        public virtual AppLogin AppLogin { get; set; }
    }
}
