//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public int AppInfoId { get; set; }
        public int TypeOfNotification { get; set; }
        public string Message { get; set; }
        public bool IsUnread { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int SubscriberId { get; set; }
    
        public virtual AppUserInfo AppUserInfo { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
