//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.LocalStringResources = new HashSet<LocalStringResource>();
            this.Locations = new HashSet<Location>();
            this.OperationSettings = new HashSet<OperationSetting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int SubscriberId { get; set; }
    
        public virtual ICollection<LocalStringResource> LocalStringResources { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual ICollection<OperationSetting> OperationSettings { get; set; }
    }
}
