//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.EmployeeRoles = new HashSet<EmployeeRole>();
            this.FormSectionRoles = new HashSet<FormSectionRole>();
            this.RoleReportsToes = new HashSet<RoleReportsTo>();
            this.RoleReportsToes1 = new HashSet<RoleReportsTo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public int SubscriberId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
        public virtual ICollection<FormSectionRole> FormSectionRoles { get; set; }
        public virtual ICollection<RoleReportsTo> RoleReportsToes { get; set; }
        public virtual ICollection<RoleReportsTo> RoleReportsToes1 { get; set; }
    }
}
