//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionEmployeeMap
    {
        public int Id { get; set; }
        public long SubmissionId { get; set; }
        public long EmployeeId { get; set; }
        public bool Assigned { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FormSubmission FormSubmission { get; set; }
    }
}
