//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        public SubscriptionPlan()
        {
            this.Subscribers = new HashSet<Subscriber>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int NumberOfUsers { get; set; }
        public int NumberOfForms { get; set; }
        public int NumberOfEntries { get; set; }
        public int NumberOfReports { get; set; }
        public int StorageLimit { get; set; }
        public decimal SubscriptionFee { get; set; }
        public int DurationInMonths { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Subscriber> Subscribers { get; set; }
    }
}
