//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormziApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public Subscriber()
        {
            this.AppLogins = new HashSet<AppLogin>();
            this.AppSettings = new HashSet<AppSetting>();
            this.Countries = new HashSet<Country>();
            this.Dashboards = new HashSet<Dashboard>();
            this.Employees = new HashSet<Employee>();
            this.FormSubmissions = new HashSet<FormSubmission>();
            this.LocalStringResources = new HashSet<LocalStringResource>();
            this.Notifications = new HashSet<Notification>();
            this.Operations = new HashSet<Operation>();
            this.SubscriberLanguages = new HashSet<SubscriberLanguage>();
            this.Forms = new HashSet<Form>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Website { get; set; }
        public string CompanyName { get; set; }
        public string SubDomain { get; set; }
        public string PreferredDomain { get; set; }
        public string Email { get; set; }
        public string CompanyLogo { get; set; }
        public string EmailVerificationCode { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long AddressId { get; set; }
        public int SubscriptionPlanId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<AppLogin> AppLogins { get; set; }
        public virtual ICollection<AppSetting> AppSettings { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Dashboard> Dashboards { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<FormSubmission> FormSubmissions { get; set; }
        public virtual ICollection<LocalStringResource> LocalStringResources { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<SubscriberLanguage> SubscriberLanguages { get; set; }
        public virtual SubscriptionPlan SubscriptionPlan { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
    }
}
